version: "3.9"

services:
  navegador-fandi:
    build: .
    container_name: navegador-fandi
    ports:
      - "8998:8080"  # host 8998, container 8080
    restart: unless-stopped
    volumes:
      - ./sessao:/root/.config
